# site settings
url: "https://zappee.github.io"
baseurl: ""
repository: "zappee/zappee.github.io"

# header configuration
title: "Remal Software"
subtitle: "Software Engineering Portfolio"
description: "Portfolio featuring my resume, projects, and AI agents."
title_separator: "|"
site_navigation: main
email: arnold.somogyi@gmail.com

# theme settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "sunrise" # air | contrast | dark | dirt | mint | sunrise | aqua | neon | plum | catppuccin_latte | catppuccin_mocha
nav_sort: page_order

# required plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# array tells Jekyll to compile specific files
include:
  - _pages
  - _includes

# company logo configuration
logo: "assets/images/remal-logo.jpg"
og_image: "assets/images/remal-logo.jpg" # The fallback branding card used for link sharing

# when you set author_profile: true, the theme pulls data directly from this block
author:
  name: "Arnold Somogyi"
  avatar: "assets/images/avatars/arnold.somogyi-profile.jpg"
  bio: "Developer, writer, and creator."
  location: "Hungary, Budapest"
  linkedin: "arnold-somogyi"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zappee"

# footer settings
name: "Copyright &copy 2020-2026 Remal Software and Arnold Somogyi All rights reserved"
# Put this in your _config.yml file
footer_text: "Feel free to check out my profiles below or reach out directly via <a href='mailto:your.email@domain.com' style='text-decoration: underline;'>email</a>."

# social media usernames (do not include the full url or @ symbol, just the raw username)
github:
  username: "zappee"
